// Generated by CoffeeScript 1.3.3
(function() {
  var Application;

  Application = require('../../src/app/application.coffee');

  describe('Application', function() {
    return it('can be required', function() {
      var app;
      app = new Application;
      return app.should.be.OK;
    });
  });

}).call(this);
