// Generated by CoffeeScript 1.3.3
(function() {
  var fs, handlebars;

  fs = require('fs');

  handlebars = require('handleify/node_modules/handlebars');

  require.extensions['.hbs'] = function(module, filename) {
    var template;
    template = handlebars.compile(fs.readFileSync(filename, 'utf8'));
    return module.exports = function(context) {
      return template(context);
    };
  };

}).call(this);
