// Generated by CoffeeScript 1.3.3
(function() {
  var app, connect, express;

  express = require('express');

  connect = require('connect');

  app = module.exports = express();

  app.configure(function() {
    app.use(connect.compress());
    app.use(express["static"](__dirname + '/public'));
    return app.use(function(req, res, next) {
      res.setHeader('Content-Type', 'charset=utf-8');
      return next();
    });
  });

  require('chalice-server')(app, require('./index.html.hbs'));

  require('./src/app/application');

  app.listen(3000);

  console.log('listening on port 3000');

}).call(this);
