// Generated by CoffeeScript 1.3.3
(function() {
  var path, server;

  path = require('path');

  server = null;

  module.exports = function(grunt) {
    this.registerTask('express-keepalive', 'keep an express server alive', function() {
      var done;
      return done = this.async();
    });
    return this.registerMultiTask('express', 'Start an express web server', function() {
      var config, done, targetConfig;
      done = this.async();
      config = grunt.config.get(this.name);
      targetConfig = config[this.target];
      if (server) {
        console.log('Killing existing Express server');
        server.kill('SIGTERM');
        server = null;
      }
      server = grunt.util.spawn({
        cmd: 'coffee',
        args: [targetConfig],
        fallback: function() {}
      }, function(err, result, code) {});
      server.stdout.on('data', function() {
        if (done) {
          done();
        }
        return done = null;
      });
      server.stdout.pipe(process.stdout);
      return server.stderr.pipe(process.stdout);
    });
  };

}).call(this);
