// Generated by CoffeeScript 1.3.3
(function() {
  var Game, game;

  Game = (function() {

    Game.prototype.width = window.innerWidth;

    Game.prototype.height = window.innerHeight;

    function Game() {
      this.setup();
    }

    Game.prototype.addPlayer = function() {};

    Game.prototype.removePlayer = function(id) {};

    Game.prototype.setup = function() {
      this.physics = new Physics();
      this.physics.integrator = new Verlet();
      this.collision = new Collision();
      this.bounds = new EdgeBounce(new Vector(0, 0), new Vector(this.width, this.height));
      return this.update();
    };

    Game.prototype.render = function() {};

    Game.prototype.update = function() {
      return this.physics.step();
    };

    return Game;

  })();

  game = new Game();

}).call(this);
